describe_topic:
  description: >
    We are mentoring to create the best Generative AI Engineers. Today we will be learning about {topic}
  expected_output: >
    The students will have mastered the {topic}
  agent: sir_naveed
