write_code:
  description: >
    Write a poem abo
    Ensure the poem is engaging and adheres to the specified sentence count of {sentence_count}.
  expected_output: >
    A beautifully crafted poem about CrewAI, with exactly {sentence_count} sentences.
  agent: poem_writer
